chore: fix docker build (#287)
antonbabenko/pre-commit-terraform pull request #288
Opened 2021-11-28 16:26 UTC by sg70

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [ x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

Fixes #287

Add missing packages (gcc and musl-dev) at docker builder stage.

### How has this code been tested

Run docker build on macOS and Ubuntu.

2021-11-28 22:49 UTC, yermulnik requested changes

2021-11-28 22:49 UTC, yermulnik commented on Dockerfile
> +    musl-dev \
`gcc` is required to build `pycares` which is what `checkov` depends on, so we only need it when `checkov` (or `INSTALL_ALL`) is enabled and we definitely not need it to be dangling in the image once `pycares` is installed (while here I also added `PYTHONUNBUFFERED` to make python output to be not buffered which is what seems to be a recommended thing for Docker images — since it's not the scope of this PR, please feel free to drop it):
```patch
diff --git a/Dockerfile b/Dockerfile
index d9141d1..d643404 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,8 @@
 ARG TAG=3.9.7-alpine3.14
 FROM python:${TAG} as builder

+ENV PYTHONUNBUFFERED 1
+
 WORKDIR /bin_dir

 RUN apk add --no-cache \
@@ -57,8 +59,10 @@ RUN if [ "$INSTALL_ALL" != "false" ]; then \
 RUN . /.env && \
     if [ "$CHECKOV_VERSION" != "false" ]; then \
     ( \
+        apk add --no-cache gcc libffi-dev musl-dev; \
         [ "$CHECKOV_VERSION" = "latest" ] && pip3 install --no-cache-dir checkov \
-        || pip3 install --no-cache-dir checkov==${CHECKOV_VERSION} \
+        || pip3 install --no-cache-dir checkov==${CHECKOV_VERSION}; \
+        apk del gcc libffi-dev musl-dev \
     ) \
     ; fi

```

2021-11-30 20:02 UTC, sg70 commented on Dockerfile
> +    musl-dev \
Your suggestions make sense. I updated the PR.

2021-11-30 20:25 UTC, yermulnik approved these changes
LGTM

2021-12-06 14:54 UTC, antonbabenko commented
Looks good to me but as a human, it does not make a lot of sense to read Dockerfile without running it.

Can we also have a GH check for pull-requests which runs `docker build` when `Dockerfile` changes and run the smoke test? No need to push it to GHCR but just getting versions should be enough. Similar to this one - https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/workflows/build-image.yaml . What do you think @yermulnik @MaxymVlasov ?

2021-12-06 14:55 UTC, merged

2021-12-06 14:57 UTC, antonbabenko commented
[v1.59.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.59.0) has been just released.

2021-12-06 17:40 UTC, yermulnik commented
> Can we also have a GH check for pull-requests …

Yeah, 100% agree. I did a build on my laptop back when I was reviewing this PR, so it should be fine to merge (what you already did though 😉).