feat: add support terraform_validate to init modules and providers if needed
antonbabenko/pre-commit-terraform pull request #301
Opened 2021-12-13 23:49 UTC by jgrumboe

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [x] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes
This PR adds logic to `terraform_validate` to detect if module initialization is needed and run it. It's also possible now to force an initialization and/or provider upgrade by just adding the documented `init-args` to the hook call.

The new logic works as follows:
`terraform providers` is called on every run and used to detect if all needed modules are initialized correctly. If it succeeds it will pass `-get=false` to the `terraform init` call, which prevents modules to be re-downloaded. On the other hand, if `terraform providers` fails, this means modules or providers are not initialized and `-get=true`will be passed to `terraform init` - a full initialization will happen.

Since `terraform init` will be called every time, the already existing `--init-args` feature will give us to additional benefits:
- `--init-args=-get=true` will result in a forced initialization on every run
- `--init-args=-upgrade` will allow to upgrade providers in addition to the modules if needed

Fixes #224 

### How has this code been tested
1. You need to have terraform code which references modules and providers.
2. Delete `.terraform` folder if present
3. Change a module version in your code to some other existing version and stage the commit
4. run `pre-commit run terraform_validate` and you see that it will initialize the `.terraform` folder newly and validate your code.
5. Every re-run of `pre-commit run terraform_validate` will be faster, as long as no module version changes happen
6. Again change a module version in your code to some other existing version and stage the commit
7. run `pre-commit run terraform_validate` and you see that it will reinitialize for the new module

Repeat the above steps with changing provider version and setting the `--init-args=-upgrade` argument. You will notice that only providers or both are initialized if needed.

2021-12-14 09:04 UTC, antonbabenko commented
Looks pretty good. Let's see what @yermulnik or @MaxymVlasov have to say after they test it locally.

2021-12-14 12:12 UTC, yermulnik approved these changes
Nice catch on using `terraform providers` to validate modules installation.
Code looks good to me.

2021-12-14 12:12 UTC, yermulnik commented on README.md
> +5. Pass the following argument, if you want `terraform_validate` hook to also upgrade all specified providers:
```suggestion
5. Pass the following argument, if you want `terraform_validate` hook to also upgrade all specified providers and (if `-get=true` is specified) to (re-)install latest versions of module(s) allowed within configured constraints:
```

2021-12-14 12:37 UTC, jgrumboe commented on README.md
> +5. Pass the following argument, if you want `terraform_validate` hook to also upgrade all specified providers:
@yermulnik  Am I allowed to commit your suggestion directly from GitHub UI or do you want to have PRs with 1 commit and force-pushed?

2021-12-14 12:41 UTC, yermulnik commented on README.md
> +5. Pass the following argument, if you want `terraform_validate` hook to also upgrade all specified providers:
I'm all fine with committing suggestions from UI (which is what they are for) if @antonbabenko as owner has no objections.

2021-12-14 12:55 UTC, antonbabenko commented on README.md
> +5. Pass the following argument, if you want `terraform_validate` hook to also upgrade all specified providers:
Looks good to me. AFAIK the PR owner (@jgrumboe) should be able to commit suggestions.

2021-12-15 12:51 UTC, MaxymVlasov requested changes

2021-12-15 12:51 UTC, MaxymVlasov commented on README.md
> +5. Pass the following argument, if you want `terraform_validate` hook to also upgrade all specified providers and (if `-get=true` is specified) to (re-)install latest versions of module(s) allowed wi
```suggestion
5. If you want `terraform_validate` hook upgrade all specified providers and install the latest versions of modules allowed within configured constraints, set:
```

2021-12-15 12:51 UTC, MaxymVlasov commented on README.md
> +    ```
```suggestion
```suggestion
    - id: terraform_validate
      args:
        - --init-args=-upgrade
        - --init-args=-get=true
    ```

    For all possible `terraform init` args, check [official docs](https://www.terraform.io/docs/cli/commands/init.html).
```

2021-12-15 12:54 UTC, MaxymVlasov commented on terraform_validate.sh
> -      if [[ ! -d .terraform ]]; then
You should return that check and add check that checks that any `--init-args` provided.


Because, time execution increased up to 80-90% for:

```yaml
repos:
- repo: git@github.com:jgrumboe/pre-commit-terraform.git
  rev: '4086982'
  hooks:
 - id: terraform_validate
 ```

compare with:

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.0
  hooks:
 - id: terraform_validate
```

2021-12-15 12:59 UTC, MaxymVlasov commented on terraform_validate.sh
> -      if [[ ! -d .terraform ]]; then
No need to run `terraform init` each time if it is not specified by arguments.
Or need to explicitly provide `force-init: true` etc. for that.

For now, it just looks like no needed speed violation.

2021-12-15 13:11 UTC, jgrumboe commented on terraform_validate.sh
> -      if [[ ! -d .terraform ]]; then
Thanks for your input.
I will try to come up with a better solution, which is fast as now when no modules/providers version changes were made in the code and still eliminates the need for manual deletion of the `.terraform` folder in case modules/providers version changes are made.

2022-02-10 20:03 UTC, MaxymVlasov commented on terraform_validate.sh
> -      if [[ ! -d .terraform ]]; then
Hi @jgrumboe 
Any updates? Do you need any help?

2022-02-12 09:35 UTC, jgrumboe commented on terraform_validate.sh
> -      if [[ ! -d .terraform ]]; then
Hi @MaxymVlasov 
Sorry, this one slipped out of my mind. I will have a look next week.
Thanks for the reminder.

2022-04-15 19:55 UTC, MaxymVlasov commented
Close as too outdated. Simpler to create a new branch with specified changes than try to resolve conflicts

2022-04-15 19:55 UTC, closed without merging