Fix/terrascan hook
antonbabenko/pre-commit-terraform pull request #305
Opened 2021-12-19 23:39 UTC by carlosbustillordguez

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [X] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [X] This PR enhances existing functionality.

### Description of your changes

This PR introduces the following changes:

- Configure `terrascan` hook to run only with Terraform config files.
- Pass to the `terrascan` command all supplied arguments.
- Allow inspecting each directory with TF config files for the current commit and fetch the final `terrascan` exit code.
- Add hook usage notes and an example for `terrascan`.

### How has this code been tested

The current implementation of `terrascan.sh` only adds to the `terrascan` command the first argument of the `ARGS` array. Try to use the following configuration to reproduce the problem (the `--policy-type azure` is never passed as an argument to `terrascan`):

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false
    # Detect compliance and security violations across IaC to mitigate risk before provisioning cloud native infrastructure.
    - id: terrascan
      args:
        - --args=--non-recursive # avoids scan errors on subdirectories without Terraform config files
        - --args=--policy-type azure
    # Security scanner for your Terraform code.
    - id: terraform_tfsec
    # A Pluggable Terraform Linter
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=--module

```

`terrascan` is executed over all committed files, which produce errors on subdirectories without Terraform config files:

```bash
$ git commit -m "test1"
Terraform validate.......................................................Passed
Terraform fmt............................................................Passed
terrascan................................................................Failed
- hook id: terrascan
- exit code: 1

2021-12-19T23:09:08.531+0100    error   cli/run.go:132  scan run failed{error 26 0  1 error occurred:
        * directory '/home/carlos/devel/azure/terraform/azure-kubernetes-services-iac/modules/cert-manager/templates' has no terraform config files

}

Terraform validate with tfsec............................................Passed
Terraform validate with tflint...........................................Passed
```

Also, only the first directory of the `FILES` array is only analyzed with `terrascan`.

2021-12-20 02:01 UTC, MaxymVlasov reviewed
docs review: Please add a link to terrascan section (`[Hook notes](#terrascan)` in Available Hooks table

2021-12-20 11:52 UTC, yermulnik commented on README.md
> +3. Use `--skip-rules strings` parameter to skip one or more rules globally while scanning (e.g.: `--args=--skip-rules="ruleID1,ruleID2"`).
```suggestion
3. Use `--skip-rules="ruleID1,ruleID2"` parameter to skip one or more rules globally while scanning (e.g.: `--args=--skip-rules="ruleID1,ruleID2"`).
```

2021-12-20 11:52 UTC, yermulnik commented on terrascan.sh
> +    ((index++)) || true
`|| true` is a bit non-obvious hack to work around how the `((expression))` works alongside `errexit`, hence I'd suggest to use more straightforward and `errexit`-independent approach:
```suggestion
    index=$((index+1))
```
Or just leave this line as is (`    let "index+=1"`).

2021-12-20 11:52 UTC, yermulnik commented on terrascan.sh
> +  # allow terrascan continue if exit_code greater than 0
```suggestion
  # allow terrascan to continue if exit_code is greater than 0
```

2021-12-20 11:52 UTC, yermulnik commented on terrascan.sh
> +    # shellcheck disable=SC2068 # terrascan fails when is used "${ARGS[@]}"
```suggestion
    # shellcheck disable=SC2068 # terrascan fails when quoting is used ("${ARGS[@]}" vs ${ARGS[@]})
```

2021-12-20 11:52 UTC, yermulnik commented on terrascan.sh
> +  set +e
```suggestion
  # preserve errexit status
  shopt -qo errexit && ERREXIT_IS_SET=true
  set +e
```

2021-12-20 11:52 UTC, yermulnik commented on terrascan.sh
> +  exit $terrascan_final_exit_code
```suggestion
  # restore errexit if it was set before the "for" loop
  [[ $ERREXIT_IS_SET ]] && set -e
  # return the terrascan final exit_code
  exit $terrascan_final_exit_code
```

2021-12-21 17:43 UTC, carlosbustillordguez commented on terrascan.sh
> +    ((index++)) || true
@yermulnik Thanks for pointing that, is good to know!

2021-12-21 18:13 UTC, yermulnik approved these changes
@MaxymVlasov Code looks good to me.

2021-12-21 18:20 UTC, MaxymVlasov commented on README.md
> +  - [License](#license)
```suggestion
* [Sponsors](#sponsors)
* [Table of content](#table-of-content)
* [How to install](#how-to-install)
  * [1. Install dependencies](#1-install-dependencies)
  * [2. Install the pre-commit hook globally](#2-install-the-pre-commit-hook-globally)
  * [3. Add configs and hooks](#3-add-configs-and-hooks)
  * [4. Run](#4-run)
* [Available Hooks](#available-hooks)
* [Hooks usage notes and examples](#hooks-usage-notes-and-examples)
  * [checkov](#checkov)
  * [infracost_breakdown](#infracost_breakdown)
  * [terraform_docs](#terraform_docs)
  * [terraform_docs_replace (deprecated)](#terraform_docs_replace-deprecated)
  * [terraform_fmt](#terraform_fmt)
  * [terraform_providers_lock](#terraform_providers_lock)
  * [terraform_tflint](#terraform_tflint)
  * [terraform_tfsec](#terraform_tfsec)
  * [terraform_validate](#terraform_validate)
  * [terrascan](#terrascan)
* [Authors](#authors)
* [License](#license)
```

2021-12-21 18:22 UTC, MaxymVlasov commented on README.md
> +  - [License](#license)
Why does it try to break the menu second time -_-


```suggestion
* [Sponsors](#sponsors)
* [Table of content](#table-of-content)
* [How to install](#how-to-install)
  * [1. Install dependencies](#1-install-dependencies)
  * [2. Install the pre-commit hook globally](#2-install-the-pre-commit-hook-globally)
  * [3. Add configs and hooks](#3-add-configs-and-hooks)
  * [4. Run](#4-run)
* [Available Hooks](#available-hooks)
* [Hooks usage notes and examples](#hooks-usage-notes-and-examples)
  * [checkov](#checkov)
  * [infracost_breakdown](#infracost_breakdown)
  * [terraform_docs](#terraform_docs)
  * [terraform_docs_replace (deprecated)](#terraform_docs_replace-deprecated)
  * [terraform_fmt](#terraform_fmt)
  * [terraform_providers_lock](#terraform_providers_lock)
  * [terraform_tflint](#terraform_tflint)
  * [terraform_tfsec](#terraform_tfsec)
  * [terraform_validate](#terraform_validate)
  * [terrascan](#terrascan)
* [Authors](#authors)
* [License](#license)
```

2021-12-21 18:25 UTC, MaxymVlasov commented on .pre-commit-hooks.yaml
> +  files: \.tf$
```suggestion
  files: \.tf$
  exclude: \.+.terraform\/.*$
```

2021-12-21 18:55 UTC, yermulnik commented on .pre-commit-hooks.yaml
> +  exclude: \.+.terraform\/.*$
@MaxymVlasov Should this be this?
```suggestion
  exclude: \.terraform\/.*$
```

2021-12-21 19:21 UTC, MaxymVlasov commented on .pre-commit-hooks.yaml
> +  exclude: \.terraform\/.*$
Improve hook speed from 2m44s to 1m 03s

```suggestion
  exclude: \.terraform\/.*$
  require_serial: true
```

2021-12-21 19:31 UTC, MaxymVlasov requested changes
Also, I tested performance, and hook in this branch work 3 times slower than in v1.62.1

took 20s 
```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.1
  hooks:
    - id: terrascan
```
tag v1.62.1 with `require_serial: true` took 9s.

took 1m 3s 
```yaml
repos:
- repo: https://github.com/carlosbustillordguez/pre-commit-terraform
  rev: 5f9e0cce9974741a7dc1723c7625082a4c1cc904
  hooks:
    - id: terrascan
```

Try to add debug outputs to script and find what goes wrong

2021-12-22 09:42 UTC, carlosbustillordguez commented on terrascan.sh
> -  terrascan_ "$ARGS" "$FILES"
Hi @MaxymVlasov, thanks for pointing that! I made the necessary corrections to return var propagation to the `terrascan_` function and pass all supplied arguments and files to that function.

2021-12-22 15:20 UTC, MaxymVlasov commented on terrascan.sh
> -  terrascan_ "$ARGS" "$FILES"
Cool, thanks

2021-12-22 15:21 UTC, MaxymVlasov commented
Still facing problems with performance. I will try investigate why

2021-12-22 15:49 UTC, carlosbustillordguez commented
> Also, I tested performance, and the hook in this branch work 3 times slower than in v1.62.1 and 6 times slower than in v1.62.2
> 
> took 20s
> 
> ```yaml
> repos:
> - repo: https://github.com/antonbabenko/pre-commit-terraform
>   rev: v1.62.1
>   hooks:
>     - id: terrascan
> ```
> 
> tag v1.62.2 (with `require_serial: true`) took 9s.
> 
> took 1m 3s
> 
> ```yaml
> repos:
> - repo: https://github.com/carlosbustillordguez/pre-commit-terraform
>   rev: 5f9e0cce9974741a7dc1723c7625082a4c1cc904
>   hooks:
>     - id: terrascan
> ```
> 
> Try to add debug outputs to script and find what goes wrong



> Also, I tested performance, and the hook in this branch work 3 times slower than in v1.62.1 and 6 times slower than in v1.62.2
> 
> took 20s
> 
> ```yaml
> repos:
> - repo: https://github.com/antonbabenko/pre-commit-terraform
>   rev: v1.62.1
>   hooks:
>     - id: terrascan
> ```
> 
> tag v1.62.2 (with `require_serial: true`) took 9s.
> 
> took 1m 3s
> 
> ```yaml
> repos:
> - repo: https://github.com/carlosbustillordguez/pre-commit-terraform
>   rev: 5f9e0cce9974741a7dc1723c7625082a4c1cc904
>   hooks:
>     - id: terrascan
> ```
> 
> Try to add debug outputs to script and find what goes wrong

I tested the hooks following the [CONTRIBUTING.md](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md) guide, against the following repos:

```bash
repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.2
    hooks:
    -   id: terrascan

repos:
-   repo: https://github.com/carlosbustillordguez/pre-commit-terraform
    rev: 0d1c7164a4cde2d8c8e3d71846a2a6a2bb4472dd
    hooks:
    -   id: terrascan
```

The tests result are:

20 runs '`terrascan` v1.62.2:'

| time command   | max    | min    | mean     | median |
| -------------- | ------ | ------ | -------- | ------ |
| users seconds  | 2.49 | 2.02 | 2.155 | 2.155 |
| system seconds | 0.23 | 0.11 | 0.17 | 0.165 |
| CPU %          | 116 | 96 | 103.5 | 104 |
| Total time     | 2.47 | 2.02 | 2.243 | 2.235 |

20 runs '`terrascan` PR #305:'

| time command   | max    | min    | mean     | median |
| -------------- | ------ | ------ | -------- | ------ |
| users seconds  | 2.3 | 1.99 | 2.1825 | 2.175 |
| system seconds | 0.25 | 0.11 | 0.1755 | 0.175 |
| CPU %          | 113 | 97 | 105.3 | 105.5 |
| Total time     | 2.46 | 2.1 | 2.2355 | 2.22 |

The total time is practically the same for both repositories. Please, note that the current implementation for `terrascan.sh` only analyze the directory of the first file passed to the `terrascan_` function:

https://github.com/antonbabenko/pre-commit-terraform/blob/04ecd10343c066e91e3c4b6d53f111a54f0363fa/terrascan.sh#L9

Because the argument is not passed as an array, in my PR I pass all arguments and files to the `terrascan_` function:

https://github.com/antonbabenko/pre-commit-terraform/blob/0d1c7164a4cde2d8c8e3d71846a2a6a2bb4472dd/terrascan.sh#L7

This can make the difference in bigger Terraform repositories because the root module and internal modules will be inspected.

Can you share which tests are you using?

2021-12-22 16:01 UTC, carlosbustillordguez commented
> Still facing problems with performance. I will try to investigate why
> 
> UPD. It is because v1.62.2 check only 1 directory, when this branch checks all. Try to decrease cont of run for terrascan

I noted that if we inspect only the first directory, works fine with a module without internal modules. For a module with internal modules, if the changed files are in different internal modules only the first one in the `FILES` array will be inspected. With the approach of my branch that is covered but I am aware can introduce some delay when all files are scanned. 

For my tests I am using a Terraform module with the following structure:

```bash
├── LICENSE
├── README.md
├── aks-cluster.tf
├── main.tf
├── modules
│   ├── agic-internal
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── cert-manager
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   ├── templates
│   │   │   ├── clusterissuer-le-production.yaml.tpl
│   │   │   ├── clusterissuer-le-staging.yaml.tpl
│   │   └── variables.tf
│   ├── kv-certificates
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   └── managed-identities-apps
│       ├── main.tf
│       ├── outputs.tf
│       ├── templates
│       │   ├── azure-identity-binding.yaml.tpl
│       │   └── azure-identity.yaml.tpl
│       └── variables.tf
├── outputs.tf
├── scripts
│   ├── README.md
│   ├── add-ssl-cert-appgw.sh
│   └── custom-role.md
├── terraform.tfvars
└── variables.tf
```

2021-12-22 16:16 UTC, MaxymVlasov commented
pre-commit automatically parallel checks to exiting cores, and I suppose you have >=4 CPU cores, when terrascan checks only 4 dirs in your repo.

Try to run on bigger repo, like this one.

```bash
.
├── README.md
├── aws-nuke.yaml
├── environment
│   ├── prd
│   │   ├── backends.tf
│   │   ├── data.tf
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   ├── providers.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   └── qa
│       ├── backends.tf
│       ├── data.tf
│       ├── main.tf
│       ├── outputs.tf
│       ├── providers.tf
│       ├── variables.tf
│       └── versions.tf
├── modules
│   ├── aws-acm-certificate
│   │   ├── acm.tf
│   │   ├── output.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-api-gateway
│   │   ├── output.tf
│   │   ├── rest.tf
│   │   ├── route53.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-chatbot
│   │   ├── README.md
│   │   ├── data.tf
│   │   ├── helm.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-dynamodb-table
│   │   ├── dynamodb.tf
│   │   ├── output.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-ecr-repo
│   │   ├── outputs.tf
│   │   ├── repo.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-eks-cluster
│   │   ├── cluster.tf
│   │   ├── data.tf
│   │   ├── iam.tf
│   │   ├── outputs.tf
│   │   ├── permissions.tf
│   │   ├── policies.tf
│   │   ├── providers.tf
│   │   ├── security.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-eks-node-group
│   │   ├── data.tf
│   │   ├── iam.tf
│   │   ├── instances.tf
│   │   ├── output.tf
│   │   ├── policies.tf
│   │   ├── security.tf
│   │   ├── user_data
│   │   │   └── userdata.sh.tpl
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-elasticache-cluster
│   │   ├── alarm.tf
│   │   ├── clusters.tf
│   │   ├── outputs.tf
│   │   ├── security.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-environment
│   │   ├── data.tf
│   │   ├── endpoints.tf
│   │   ├── flow_log.tf
│   │   ├── iam.tf
│   │   ├── instances.tf
│   │   ├── lambdas.tf
│   │   ├── network.tf
│   │   ├── outputs.tf
│   │   ├── policies.tf
│   │   ├── provisioner.tf
│   │   ├── route53.tf
│   │   ├── security.tf
│   │   ├── sns.tf
│   │   ├── templates
│   │   │   └── github-users-sync.tpl
│   │   ├── user_data
│   │   │   └── bastion.sh
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-gitlab-ec2-manager
│   │   ├── README.md
│   │   ├── ec2.tf
│   │   ├── iam.tf
│   │   ├── outputs.tf
│   │   ├── provisioner.tf
│   │   ├── s3.tf
│   │   ├── sg.tf
│   │   ├── templates
│   │   │   ├── config.sh
│   │   │   └── init.sh
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-grafana
│   │   ├── alarm.tf
│   │   ├── data.tf
│   │   ├── db.tf
│   │   ├── helm.tf
│   │   ├── iam.tf
│   │   ├── providers.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-iam-group
│   │   ├── iam.tf
│   │   ├── outputs.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-iam-role
│   │   ├── iam.tf
│   │   ├── outputs.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-iam-user
│   │   ├── iam.tf
│   │   ├── outputs.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-lambda-function
│   │   ├── cloudwatch.tf
│   │   ├── iam.tf
│   │   ├── lambda.tf
│   │   ├── output.tf
│   │   ├── permissions.tf
│   │   ├── policy.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-msk-cluster
│   │   ├── cloudwatch.tf
│   │   ├── kms.tf
│   │   ├── msk.tf
│   │   ├── outputs.tf
│   │   ├── security.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-rds-cluster
│   │   ├── alarm.tf
│   │   ├── iam.tf
│   │   ├── instances.tf
│   │   ├── outputs.tf
│   │   ├── policies.tf
│   │   ├── security.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-route53-zone
│   │   ├── outputs.tf
│   │   ├── variables.tf
│   │   ├── versions.tf
│   │   └── zone.tf
│   ├── aws-s3-bucket
│   │   ├── iam.tf
│   │   ├── outputs.tf
│   │   ├── policy.tf
│   │   ├── s3.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── aws-sns-topic
│   │   ├── output.tf
│   │   ├── sns.tf
│   │   ├── variable.tf
│   │   └── versions.tf
│   ├── helm-release
│   │   ├── helm.tf
│   │   ├── namespace.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── kube-manifest
│   │   ├── manifest.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── postgresql-env
│   │   ├── db.tf
│   │   ├── outputs.tf
│   │   ├── variables.tf
│   │   └── versions.tf
│   └── rapp-services
│       ├── aws-core-api
│       │   ├── README.md
│       │   ├── data.tf
│       │   ├── db.tf
│       │   ├── helm.tf
│       │   ├── iam.tf
│       │   ├── vars.tf
│       │   └── versions.tf
│       ├── aws-iot-segway-max-plus
│       │   ├── README.md
│       │   ├── data.tf
│       │   ├── helm.tf
│       │   ├── vars.tf
│       │   └── versions.tf
│       ├── aws-iot-segway-mock
│       │   ├── README.md
│       │   ├── data.tf
│       │   ├── db.tf
│       │   ├── helm.tf
│       │   ├── variables.tf
│       │   └── versions.tf
│       └── aws-ops-web
│           ├── README.md
│           ├── alarm.tf
│           ├── helm.tf
│           ├── providers.tf
│           ├── variables.tf
│           └── versions.tf
├── path
├── results.json
├── run-305.sh
├── run1.62.2.sh
├── run305-dir.sh
├── services
│   ├── alerting
│   │   └── us-east-1
│   │       ├── init.tf
│   │       ├── main.tf
│   │       └── vars.tf
│   ├── chatbot
│   │   └── global
│   │       ├── 0-init.tf
│   │       ├── 1-ssm-params.tf
│   │       ├── 2-eks.tf
│   │       ├── 3-api-gw.tf
│   │       ├── 3-iam.tf
│   │       ├── 3-lambda.tf
│   │       └── vars.tf
│   ├── dns
│   │   └── global
│   │       ├── backends.tf
│   │       ├── main.tf
│   │       ├── outputs.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── docker-registry
│   │   └── global
│   │       ├── backends.tf
│   │       ├── main.tf
│   │       ├── outputs.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── grafana
│   │   └── qa
│   │       ├── backends.tf
│   │       ├── data.tf
│   │       ├── main.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── iam
│   │   └── global
│   │       ├── backends.tf
│   │       ├── data.tf
│   │       ├── main.tf
│   │       ├── outputs.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── kafka
│   │   ├── prd
│   │   │   ├── init.tf
│   │   │   ├── main.tf
│   │   │   ├── outputs.tf
│   │   │   └── vars.tf
│   │   └── qa
│   │       ├── backends.tf
│   │       ├── data.tf
│   │       ├── main.tf
│   │       ├── outputs.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── kubernetes
│   │   ├── README.md
│   │   ├── prd
│   │   │   ├── backends.tf
│   │   │   ├── data.tf
│   │   │   ├── kube-prometheus-stack.yaml
│   │   │   ├── main.tf
│   │   │   ├── outputs.tf
│   │   │   ├── providers.tf
│   │   │   ├── variables.tf
│   │   │   └── versions.tf
│   │   └── qa
│   │       ├── backends.tf
│   │       ├── data.tf
│   │       ├── kube-prometheus-stack.yaml
│   │       ├── main.tf
│   │       ├── outputs.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── postgresql
│   │   └── qa
│   │       ├── backends.tf
│   │       ├── data.tf
│   │       ├── main.tf
│   │       ├── outputs.tf
│   │       ├── providers.tf
│   │       ├── variables.tf
│   │       └── versions.tf
│   ├── rapp
│   │   ├── prd
│   │   │   └── p-1
│   │   │       ├── core-api
│   │   │       │   ├── init.tf
│   │   │       │   ├── main.tf
│   │   │       │   └── vars.tf
│   │   │       ├── iot-segway-max-plus
│   │   │       │   ├── init.tf
│   │   │       │   ├── main.tf
│   │   │       │   └── vars.tf
│   │   │       └── ops-web
│   │   │           ├── init.tf
│   │   [...]

2021-12-22 17:33 UTC, carlosbustillordguez commented
> Still facing problems with performance. I will try to investigate why
> 
> UPD. It is because v1.62.2 check only 1 directory, when this branch checks all. Try to decrease cont of run for terrascan

I just changed the code to scan only one directory:

https://github.com/antonbabenko/pre-commit-terraform/blob/677912bfd5aa16792c00cab160982fa472eb06d0/terrascan.sh#L15-L22

It will be good to catch if the `terrascan try-repo` was issued with the `-a` argument, to only run `terrascan` in the first directory otherwise, run in directories with changed .tf files. But I don't know how to do that... any clue?

Please, let me know if the new change has improved the performance for your repo.

2021-12-22 18:29 UTC, MaxymVlasov approved these changes
I little bit check how `terrascan` works and what I found:
`terrascan` recursively check all files in provided dir.


So performance degradation exists only in the `pre-commit run --all` situation, because it will provide all existing files to hook:

https://github.com/antonbabenko/pre-commit-terraform/blob/e6ffbcd3def77c7caa471d008daefa13f9095127/terrascan.sh#L15-L19

Then, unique paths are found and run `terrascan` for each folder:

https://github.com/antonbabenko/pre-commit-terraform/blob/e6ffbcd3def77c7caa471d008daefa13f9095127/terrascan.sh#L29-L30

It works literally how it should work: checks only diffs.

At the same time, need to know when the `--all` (`-a`) argument passed to `pre-commit` and just run `terrascan -d GIT_REPO_ROOT`.
Because it is not very related to this PR, I propose to merge that PR as is, and open issue for improving performance during `pre-commit -a` run.
 
Because for now
>only the first directory of the FILES array is only analyzed with `terrascan`.

And that is not a performance issue in day-to-day usage cases, it's a bug that should be fixed.

@carlosbustillordguez if you'd like to fix that too, you're welcome to fix #309, right after this PR merge.


@antonbabenko ready to merge

2021-12-22 18:34 UTC, antonbabenko commented
@MaxymVlasov Could you please write a bit more descriptive title for the PRs? What exactly does this PR fix in the hook? It will be used in CHANGELOG and release notes.

2021-12-22 18:37 UTC, MaxymVlasov commented
@antonbabenko done

2021-12-22 18:44 UTC, antonbabenko commented
Keep in mind the length. :)

2021-12-22 18:44 UTC, merged

2021-12-22 18:45 UTC, antonbabenko commented
This PR is included in version 1.62.3 :tada:

2021-12-22 18:56 UTC, MaxymVlasov commented
@carlosbustillordguez thank you for help during debugging.