chore: Google Shell Style Compliance
antonbabenko/pre-commit-terraform pull request #326
Opened 2022-01-12 20:31 UTC by mohitsaxenaknoldus

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [ ] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [x] This PR enhances existing functionality.

### Description of your changes
This PR only contains small non-breaking changes. I'll create another PR which will require some careful testing.
#324 

### How can we test changes

2022-01-12 20:46 UTC, yermulnik commented on hooks/_common.sh
> +function common::initialize() {
it's either `function name {` or `name () {`:
```
> help function | head -1
function: function name { COMMANDS ; } or name () { COMMANDS ; }
```

2022-01-12 20:46 UTC, yermulnik commented on hooks/infracost_breakdown.sh
> +  read -r -a args <<<"$2"
The whitespace reduction changes is what shellcheck GH action refuses to accept.

2022-01-12 20:46 UTC, yermulnik commented on hooks/infracost_breakdown.sh
> +function main() {
It might be my very personal convenience pref but `main` function definition in the very beginning help to quickly figure out the order other functions get called in.

2022-01-19 13:10 UTC, yermulnik commented on hooks/terragrunt_fmt.sh
> +# Unique part of `common::per_dir_hook`. The  is executed in loop
I think either `function` word should be put back or replace `The` with `This`.

2022-01-19 13:10 UTC, yermulnik commented on hooks/_common.sh
> +common::initialize() {
The `name()` to `function name` change was an effort by @MaxymVlasov 
Please negotiate this with Max.

2022-01-19 13:12 UTC, yermulnik commented on hooks/infracost_breakdown.sh
> +  read -r -a args <<<"$2"
Would you please pet linter by reverting such whitespace change along with fix other linter errors and warnings.

2022-01-20 14:16 UTC, MaxymVlasov requested changes

2022-01-20 14:20 UTC, MaxymVlasov commented on hooks/_common.sh
> +common::initialize() {
Ah, George mentined that `()` will not works within `function` 
https://github.com/antonbabenko/pre-commit-terraform/pull/326#discussion_r783428265

2022-02-10 20:11 UTC, closed without merging