fix: Print out the full path in tflint when run through pre-commit
antonbabenko/pre-commit-terraform pull request #357
Opened 2022-04-07 13:54 UTC by thomaslast

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

This PR aims to fix the issue here: https://github.com/antonbabenko/pre-commit-terraform/issues/54

The issue for tflint is resolved by running the pre-commit at the repo level and the full path is then displayed on an error. 

### How can we test changes

```yaml
repos:
- repo: https://github.com/thomaslast/pre-commit-terraform
  rev: afde258978090e4d2382fd90bb230347d0b349ac
```

✅ Work as expected 
☑️ - Able to check only passed, not fail scenario
✖️ - work, but not print full path
❌ - failed to start
Not checked

✅ `checkov` (python, not affected hook)
✅ `infracost_breakdown`
✅ `terraform_docs_replace` (deprecated, python, not affected hook)
✖️ `terraform_docs_without_aggregate_type_defaults`
✖️  `terraform_docs`
✅  `terraform_fmt`
❌ `terraform_providers_lock`
❌   `terraform_tflint`
✅  `terraform_tfsec`
☑️  `terraform_validate`
✖️  `terragrunt_fmt`
☑️  `terragrunt_validate`
❌  `terrascan`

2022-04-08 09:41 UTC, thomaslast commented on hooks/_common.sh
> +    [ -f "$dir_path" ] || continue
I've added in the dir_path so that it should run against the file for each hook

2022-04-08 09:41 UTC, thomaslast commented on hooks/_common.sh
> +    [ -f "$dir_path" ] || continue
I've added in the dir_path so that it should run against the file for each hook

2022-04-11 12:18 UTC, yermulnik reviewed
I added some more comments re the new portion of changes — please take a look.
Also could you please test-run all hooks you're requesting changes too and provide the output, so that we are sure there's no breakage of existing functionality which may impact other consumers of `pre-commit-terraform`. Thank you.

@MaxymVlasov Could you please take a look into this PR when you've got a chance so that we all agree upon this kind of changes? Thanks.

2022-04-11 12:18 UTC, yermulnik commented on hooks/terragrunt_fmt.sh
> +  terragrunt hclfmt ${args[@]} "$dir_path"
Based on https://terragrunt.gruntwork.io/docs/reference/cli-options/#hclfmt this wouldn't work for `terragrunt`. The `hclfmt` recursively searches current working dir and isn't compatible with providing target working dir as a command line argument, hence the `terragrunt hclfmt` hook need an explicit `pushd`/`popd` workaround.

2022-04-11 12:18 UTC, yermulnik commented on hooks/terrascan.sh
> +  terrascan scan -i terraform ${args[@]} "$dir_path"
To provide target working directory to `terrascan` the `-d, --iac-dir string` command line flag must be provided:
```
> terrascan scan -h | fgrep -- --iac-dir
  -d, --iac-dir string            path to a directory containing one or more IaC files (default ".")
```
Please fix.

2022-04-13 19:19 UTC, MaxymVlasov requested changes
Good try, but that will not work, because you are already in `$dir_path`. Usage of `"$(pwd)"` will not help too:

```bash
Oslo/environment/qa ➜ terraform fmt "$(pwd)"      
main.tf
````

You need to show an error msg like "that was changed in next dir" but not show it if exit code == 0

2022-04-13 19:22 UTC, MaxymVlasov commented on hooks/_common.sh
> +    [ ! -d "$dir_path" ] && continue
Hmm, not mention that. Lmc

2022-04-13 19:36 UTC, MaxymVlasov commented on hooks/_common.sh
> +    [ ! -d "$dir_path" ] && continue
Yeah, with that change it can work, but need to check that all hooks will work properly

2022-04-13 19:46 UTC, MaxymVlasov commented
Hmm, it does not print changed files at all, interesting

```bash
➜ pre-commit run
Terraform docs...........................................................Failed
- hook id: terraform_docs
- files were modified by this hook
```

```bash
repos:
- repo: https://github.com/thomaslast/pre-commit-terraform
  rev: afde258978090e4d2382fd90bb230347d0b349ac
  hooks:
    - id: terraform_docs
```

2022-04-13 20:06 UTC, MaxymVlasov commented on hooks/_common.sh
> +    [ ! -d "$dir_path" ] && continue
TFLint can't find TF modules by relative `source` without `pushd`

2022-04-13 20:38 UTC, MaxymVlasov commented on hooks/_common.sh
> +    [ ! -d "$dir_path" ] && continue
```yaml
repos:
- repo: https://github.com/thomaslast/pre-commit-terraform
  rev: afde258978090e4d2382fd90bb230347d0b349ac
```

✅ Work as expected 
☑️ - Able to check only passed, not fail scenario
✖️ - work, but not print full path
❌ - failed to start
Not checked

✅ `checkov` (python, not affected hook)
✅ `infracost_breakdown`
✅ `terraform_docs_replace` (deprecated, python, not affected hook)
✖️ `terraform_docs_without_aggregate_type_defaults`
✖️  `terraform_docs`
✅  `terraform_fmt`
❌ `terraform_providers_lock`
❌   `terraform_tflint`
✅  `terraform_tfsec`
✅  `terraform_validate`
✖️  `terragrunt_fmt`
☑️  `terragrunt_validate`
❌  `terrascan`

2022-04-27 10:17 UTC, thomaslast commented
Sorry I've gone AWOL on this, thanks @MaxymVlasov and @yermulnik for your help on this. This seems to be breaking change for something that could be quite simple. Is it worth making another version of `common::per_dir_hook` which will not use pushd & popd that I make use of just for tflint for the moment...?

2022-06-08 00:13 UTC, closed without merging