fix: Fix terraform_wrapper_module_for_each for when resource name contains 'variable'
antonbabenko/pre-commit-terraform pull request #573
Opened 2023-09-21 17:43 UTC by nshenry03

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

There are some providers with resources and data sources that have "variable" in their name, for example:

- [env0_configuration_variable](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable)
- [env0_configuration_variable](https://registry.terraform.io/providers/env0/env0/latest/docs/data-sources/configuration_variable) data source

When using such resources, `terraform_wrapper_module_for_each` was adding these as variables to pass in `wrappers/main.tf` which breaks the wrapper 

> ╷
> │ Error: Unsupported argument
> │ 
> │   on main.tf line 14, in module "wrapper":
> │   14:   env0_configuration_variable              = try(each.value.env0_configuration_variable, var.defaults.env0_configuration_variable)
> │ 
> │ An argument named "env0_configuration_variable" is not expected here.
> ╵
> Validation failed: wrappers

My fix simply improves `grep` to ensure that `module_vars` (and `module_outputs` and `module_providers`) only find actual variables, outputs, and providers and NOT resources.

### How can we test changes

Use the examples provided in the documentation for [env0_configuration_variable](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable) and try `terraform_wrapper_module_for_each` as-is today.  You'll see that it adds these as variables to pass to the module when it shouldn't.

Now test with my fix and you'll see that it fixes the issue.

2023-09-21 17:57 UTC, antonbabenko requested changes

2023-09-21 17:57 UTC, antonbabenko commented on hooks/terraform_wrapper_module_for_each.sh
> +    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^\s*variable." | cut -d'.' -f 2 | sort || true; }))
```suggestion
    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^variable." | cut -d'.' -f 2 | sort || true; }))
```
This should be enough. I don't think there can/should be any space before the "variable".

Please apply the same fix on other lines in this PR.

2023-09-21 18:46 UTC, yermulnik commented on hooks/terraform_wrapper_module_for_each.sh
> +    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^\s*variable." | cut -d'.' -f 2 | sort || true; }))
> I don't think there can/should be any space before the "variable".

Leading spaces do not produce errors, trigger failures and are not otherwise disallowed explicitly. Hence should be considered allowed imho.
On the other end `hcledit block list` seems to strip leading spaces, which means Anton's recommendation is correct =)

2023-09-21 18:46 UTC, yermulnik commented on hooks/terraform_wrapper_module_for_each.sh
> +    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^\s*variable." | cut -d'.' -f 2 | sort || true; }))
I also would like to recommend to escape dot to not mix it with "any char" in this use case:
```suggestion
    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^variable\." | cut -d'.' -f 2 | sort || true; }))
```

2023-09-21 18:46 UTC, yermulnik commented on hooks/terraform_wrapper_module_for_each.sh
> +    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^\s*variable." | cut -d'.' -f 2 | sort || true; }))
And as Anton mentioned: please apply the same to other code bits in this PR.

2023-09-21 22:52 UTC, nshenry03 commented on hooks/terraform_wrapper_module_for_each.sh
> +    module_vars=($(echo "$all_tf_content" | hcledit block list | { grep "^\s*variable." | cut -d'.' -f 2 | sort || true; }))
Done! Please resolve if this looks sufficient. Thanks!

2023-09-21 23:00 UTC, yermulnik approved these changes

2023-09-22 07:17 UTC, antonbabenko approved these changes

2023-09-22 07:18 UTC, merged

2023-09-22 07:18 UTC, antonbabenko commented
This PR is included in version 1.83.4 :tada: