fix(terraform_docs): Always use GNU sed
antonbabenko/pre-commit-terraform pull request #704
Opened 2024-08-29 07:24 UTC by cschroer

Ensure compatibility of `terraform_docs` hook on MacOS and Linux by using GNU sed.

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

In PR #701, the usage of `sed` was introduced to the `terraform_docs` for in-file changes, resulting in #703

MacOS requires an extension for the `-i` parameter, unlike GNU sed.
As a result the hook fails on MacOS know with the following error:

```shell
Terraform docs..........................................................................Failed
- hook id: terraform_docs
- exit code: 1

sed: 1: "README.md": invalid command code R
```

I see two potential solutions for this issue.

1) Always pass a extension to the `-i` parameter, as this is compatible with GNU sed, too. As a result, a backup file would be created for each sed commands operation and needs to be deleted again.

2) Ensure we always use GNU sed. GNU sed is available via brew and can easily be installed on MacOS systems. Using GNU sed on both MacOS and Linux ensures consistent behaviour across operating systems.

I'm happy to change it to option 1, but wanted to show both options I see to fix the issue. Also I'm not 100% sure about Windows support for this hooks, but it seems like ( #648 ) they only work on Linux and MacOS.

2024-08-29 10:22 UTC, drAlberT commented
@cschroer there is a much more easy solution (I use this since many years and it is proven to be portable) ...

When you use "-i" in sed you must always add the backup suffix otherwise it would not work on Mac for example. Adding and empty suffix does the trick:

```shell
# bad
infra albert$ sed -i "s/^ASDDFGFDSGHSDFG$/PIPPOPIPPO/" "MODULE-DETAILS.md" 
sed: 1: "MODULE-DETAILS.md": invalid command code M

#good
infra albert$ sed -i "" "s/^ASDDFGFDSGHSDFG$/PIPPOPIPPO/" "MODULE-DETAILS.md"
infra albert$
```

2024-08-29 12:30 UTC, yermulnik requested changes

2024-08-29 12:30 UTC, yermulnik commented on hooks/terraform_docs.sh
> +  ${SED_COMMAND} -i "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
We can use POSIX `sed` on both platforms:
```suggestion
  sed -i'' -e "s/^${old_insertion_marker_begin}$/${insertion_marker_begin}/" "$file"
  sed -i'' -e "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
```

2024-08-29 12:39 UTC, MaxymVlasov commented
And I suppose we need same fix in https://github.com/cschroer/pre-commit-terraform/blob/ad5d40b6686386e930560851f12b670df7110828/README.md#L585-L590

2024-08-29 12:51 UTC, cschroer commented
I personally ran into some other issues with sed on MacOS, therefor I personally prefer using GNU sed on MacOS, too.
But for this case it's maybe better to simply use the empty extension. 👍 Adjusted the code and also updated the README.

2024-08-29 13:04 UTC, yermulnik commented on README.md
> +      grep -rl 'END OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs sed -i'' 's/END OF PRE-COMMIT-TERRAFORM DOCS HOOK/END_TF_DOCS/g'
Also, @MaxymVlasov, what do you think of adding `--null` to `grep` and `-0` to `xarges` to correctly handle files with whitrespace chars in names (if there any might exist in users' configuration)?
```suggestion
      grep -rl --null 'BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs -0 sed -i'' 's/BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK/BEGIN_TF_DOCS/g'
      grep -rl --null 'END OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs -0 sed -i'' 's/END OF PRE-COMMIT-TERRAFORM DOCS HOOK/END_TF_DOCS/g'
```

ℹ️ Using long opt (`--null`) to maintain compatibility with BSD `grep`.

2024-08-29 15:01 UTC, drAlberT commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
As in my previous comment, there must be a space in `-i ''`. I was using it some years ago, but it stopped working on Mac.
![Screenshot 2024-08-29 at 17 00 48](https://github.com/user-attachments/assets/89bd7d7d-42d3-4430-99df-a7754837d485)

2024-08-29 15:07 UTC, yermulnik commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
This fails for me on GNU `sed`, whilst `… -i'' -e …` does not.

2024-08-29 15:15 UTC, drAlberT commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
What about using `perl -ie` instead?

2024-08-29 15:25 UTC, yermulnik commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
* `sed` is more likely to be part of base system
* Using language interpreter to do what stream editor can do looks odd to me
* `sed` is sufficient by adhering with GNU and non-GNU implementations (see my commit suggestions above)

2024-08-29 15:29 UTC, drAlberT commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
I get your point, but perl is part of any unix since K&R I think .. anyway, how to solve then?

The portable alternative is to create a temporary file and avoid working in place.

2024-08-29 15:34 UTC, yermulnik commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
> I get your point, but perl is part of any unix since K&R I think ..

I don't think Perl is part of **any** NIX unless installed by user.

> anyway, how to solve then?
> The portable alternative is to create a temporary file and avoid working in place.

The `sed -i'' -e 's/string/replacement/' file` works for me on both GNU and BSD `sed`.

2024-08-29 15:46 UTC, drAlberT commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
I agree that perl is not POSIX so it's not an option...

As I reported the other option is not working on my Mac and I don't think it would be the case to *require* to install GNU sed on Mac.

IMHO the only real solution is to create a temporary file (which, of course, sed does behind the hoods for us). 

`sed -e 's/string/replacement/' file > tmp-file && mv tmp-file file`

2024-08-29 16:03 UTC, yermulnik commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
> As I reported the other option is not working on my Mac and I don't think it would be the case to _require_ to install GNU sed on Mac.

Which "other option"? From what you posted above in this thread I don't see the `sed -i'' -e 's/string/replacement/' file` thing (notice the `-e` arg).

2024-08-29 16:08 UTC, MaxymVlasov commented on README.md
> +      grep -rl 'END OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs sed -i'' 's/END OF PRE-COMMIT-TERRAFORM DOCS HOOK/END_TF_DOCS/g'
I'm OK till it works :)

2024-08-29 16:14 UTC, MaxymVlasov commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
How about
```sh
SED_CMD=$(sed --version >/dev/null 2>&1 && echo "sed -i''" || echo "sed -i ''")
$SED_CMD -e "s/^${old_insertion_marker_begin}$/${insertion_marker_begin}/" "$file"
```
?

2024-08-29 16:24 UTC, yermulnik commented on README.md
> +      grep -rl 'END OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs sed -i'' 's/END OF PRE-COMMIT-TERRAFORM DOCS HOOK/END_TF_DOCS/g'
@cschroer Please commit most recent suggestion from this thread and see if it works for you w/o issues. Thanks.

2024-08-29 16:29 UTC, MaxymVlasov commented on README.md
> +      grep -rl 'END OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs sed -i'' 's/END OF PRE-COMMIT-TERRAFORM DOCS HOOK/END_TF_DOCS/g'
If sed will not work, replace it to
```sh
      SED_CMD=$(sed --version >/dev/null 2>&1 && echo "sed -i''" || echo "sed -i ''")
      grep -rl --null 'BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs -0 $SED_CMD -e 's/BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK/BEGIN_TF_DOCS/'
      grep -rl --null 'END OF PRE-COMMIT-TERRAFORM DOCS HOOK' . | xargs -0  $SED_CMD -e 's/END OF PRE-COMMIT-TERRAFORM DOCS HOOK/END_TF_DOCS/'
```

2024-08-29 16:30 UTC, yermulnik commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
@MaxymVlasov I don't see a reason for this quirk as @drAlberT hasn't provided `sed -i'' -e 's/string/replacement/' file` indeed does **NOT** work on macOS.
I was under impression that macOS has the similar BSD tools as FreeBSD has (at least mostly), where I verified BSD `sed` to work with `sed -i'' -e 's/string/replacement/' file`.

2024-08-29 16:45 UTC, MaxymVlasov commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
Aha, I just grub some volunteers with Mac, and looks like it works for them

![image](https://github.com/user-attachments/assets/a9093426-4788-4a4c-a780-2bee6e326ed5)![image](https://github.com/user-attachments/assets/babc0b02-2851-4b2b-a580-836847bc7de3)

2024-08-29 16:52 UTC, robinbowes commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
I can confirm that both the following work OK on my Mac:

Mac sed:
```
sed -i'' -e 's/foo/foobar/' tt.txt
```

Gnu sed:
```
gsed -i'' -e 's/foo/foobar/' tt.txt
```

2024-08-29 16:57 UTC, MaxymVlasov approved these changes

2024-08-29 17:01 UTC, MaxymVlasov commented
>Also I'm not 100% sure about Windows support for this hooks, but it seems like ( https://github.com/antonbabenko/pre-commit-terraform/issues/648 ) they only work on Linux and MacOS.

@cschroer yep, you're right
From installation instructions,
https://github.com/antonbabenko/pre-commit-terraform/blob/99fceb87b07cdbb97111c3b4eb17d3f70d36e13c/README.md#L207-L213

2024-08-29 18:01 UTC, yermulnik approved these changes

2024-08-29 19:31 UTC, merged

2024-08-29 19:32 UTC, antonbabenko commented
This PR is included in version 1.93.1 :tada:

2024-08-30 08:38 UTC, drAlberT commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
> > As I reported the other option is not working on my Mac and I don't think it would be the case to _require_ to install GNU sed on Mac.
> 
> Which "other option"? From what you posted above in this thread I don't see the `sed -i'' -e 's/string/replacement/' file` thing (notice the `-e` arg).

You are right, my bad sorry .. the trick is to add -e and it works also on my Mac.

![Screenshot 2024-08-30 at 10 38 02](https://github.com/user-attachments/assets/c1a94f26-6a25-41fd-8310-cfe8bd151689)


Apologies

2024-08-30 08:51 UTC, drAlberT commented on hooks/terraform_docs.sh
> +  sed -i''  "s/^${old_insertion_marker_end}$/${insertion_marker_end}/" "$file"
![Screenshot 2024-08-30 at 10 46 40](https://github.com/user-attachments/assets/cae94f41-61a8-4457-92f1-4f57d3fe80c0)